# Generated by Django 5.1.4 on 2025-02-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakultets',
            options={'ordering': ['-created_at']},
        ),
    ]
