# Generated by Django 5.1.6 on 2025-04-09 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='fakultet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guruh',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kurs',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yonalish',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guruh',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='users.kurs'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to='users.yonalish'),
        ),
        migrations.AlterField(
            model_name='users',
            name='fakultet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.fakultet'),
        ),
        migrations.AlterField(
            model_name='yonalish',
            name='fakultet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonalishlar', to='users.fakultet'),
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('familya', models.CharField(blank=True, max_length=255)),
                ('ism', models.CharField(blank=True, max_length=255)),
                ('nomer', models.CharField(blank=True, max_length=255)),
                ('sardor', models.BooleanField(default=False)),
                ('jins', models.CharField(blank=True, choices=[('o`g`il', 'o`g`il'), ('qiz', 'qiz')], max_length=255)),
                ('tolov_status', models.CharField(blank=True, choices=[('grand', 'grand'), ('kontrakt', 'kontrakt')], max_length=255)),
                ('ijtimoiy_ximoya', models.CharField(blank=True, max_length=255)),
                ('ijtimoiy_daraja', models.CharField(blank=True, max_length=255)),
                ('iqdidorli_talaba', models.CharField(blank=True, max_length=255)),
                ('guruh', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='talabalar', to='users.guruh')),
                ('tyutor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
