# Generated by Django 5.1.6 on 2025-03-05 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_fakultet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='guruh',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='users.kurs'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to='users.yonalish'),
        ),
        migrations.AlterField(
            model_name='yonalish',
            name='fakultet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonalishlar', to='users.fakultet'),
        ),
    ]
