# Generated by Django 5.1.4 on 2024-12-13 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_parol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='fakultet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.fakultets'),
        ),
    ]
