# Generated by Django 5.1.4 on 2024-12-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_parol'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='parol',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
