# Generated by Django 5.1.4 on 2025-02-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_fakultet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fakultets',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
