# Generated by Django 5.1.6 on 2025-03-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_options_alter_guruh_kurs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakultet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guruh',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kurs',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yonalish',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
