# Generated by Django 5.1.4 on 2024-12-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_fakultet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='users',
            name='superadmin',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tyutr',
        ),
        migrations.AddField(
            model_name='users',
            name='rol',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
