# Generated by Django 5.1.4 on 2025-02-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_fakultets_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('superadmin', 'superadmin'), ('admin', 'admin'), ('tutor', 'tutor')], max_length=30),
        ),
    ]
