# Generated by Django 5.1.6 on 2025-03-22 04:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fakultet_is_active_guruh_is_active_kurs_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('familya', models.CharField(blank=True, max_length=255)),
                ('ism', models.CharField(blank=True, max_length=255)),
                ('nomer', models.CharField(blank=True, max_length=255)),
                ('sardor', models.BooleanField(default=False)),
                ('jins', models.CharField(blank=True, choices=[('o`g`il', 'o`g`il'), ('qiz', 'qiz')], max_length=255)),
                ('tolov_status', models.CharField(blank=True, choices=[('grand', 'grand'), ('kontrakt', 'kontrakt')], max_length=255)),
                ('ijtimoiy_ximoya', models.CharField(blank=True, max_length=255)),
                ('ijtimoiy_daraja', models.CharField(blank=True, max_length=255)),
                ('iqdidorli_talaba', models.CharField(blank=True, max_length=255)),
                ('guruh', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='talabalar', to='users.guruh')),
                ('tyutor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
