# Generated by Django 5.1.6 on 2025-02-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_guruh_kurs_yonalish_rename_fakultets_fakultet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='guruh',
            field=models.ManyToManyField(blank=True, to='users.guruh'),
        ),
    ]
