# Generated by Django 5.1.6 on 2025-02-19 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_guruh'),
    ]

    operations = [
        migrations.AddField(
            model_name='guruh',
            name='kurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.kurs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurs',
            name='yonalish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.yonalish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yonalish',
            name='fakultet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.fakultet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kurs',
            name='name',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30),
        ),
    ]
