# Generated by Django 5.1.6 on 2025-02-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_guruh_kurs_kurs_yonalish_yonalish_fakultet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='guruh',
            field=models.ManyToManyField(blank=True, related_name='guruh', to='users.guruh'),
        ),
    ]
