# Generated by Django 5.1.6 on 2025-02-28 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MajburiyTopshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tur', models.CharField(choices=[('ttjga_tashrif', 'ttjga_tashrif'), ('ijaraga_tashrif', 'ijaraga_tashrif'), ('tutorlik_soati', 'tutorlik_soati'), ('davra_suhbati', 'davra_suhbati'), ('tadbir', 'tadbir'), ('ttjda_tadbir', 'ttjda_tadbir'), ('iqtidorli_talabam', 'iqtidorli_talabam'), ('oilaga_xat', 'oilaga_xat'), ('test', 'test')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('baxo', models.IntegerField(default=0)),
                ('file1', models.FileField(blank=True, null=True, upload_to='topshiriq/majburiy')),
                ('file2', models.FileField(blank=True, null=True, upload_to='topshiriq/majburiy')),
                ('file3', models.FileField(blank=True, null=True, upload_to='topshiriq/majburiy')),
                ('file4', models.FileField(blank=True, null=True, upload_to='topshiriq/majburiy')),
                ('baxolash', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OzSohasidaTopshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baxo', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file2', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file3', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file4', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('baxolash', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OzXohishiBilanTopshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baxo', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file2', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file3', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file4', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('baxolash', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QoshimchaTopshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baxo', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file2', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file3', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file4', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('baxolash', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topshiriq_turi', models.CharField(choices=[('majburiy', 'majburiy'), ('qoshimcha', 'qoshimcha'), ('oz_sohasida', 'oz_sohasida')], default='qoshimcha', max_length=30)),
                ('majburiy_topshiriq_turi', models.CharField(blank=True, choices=[('ttjga_tashrif', 'ttjga_tashrif'), ('ijaraga_tashrif', 'ijaraga_tashrif'), ('tutorlik_soati', 'tutorlik_soati'), ('davra_suhbati', 'davra_suhbati'), ('tadbir', 'tadbir'), ('ttjda_tadbir', 'ttjda_tadbir'), ('iqtidorli_talabam', 'iqtidorli_talabam'), ('oilaga_xat', 'oilaga_xat'), ('test', 'test')], max_length=30, null=True)),
                ('topshiriq_soni', models.IntegerField(default=1)),
                ('max_baxo', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq')),
                ('file2', models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq')),
                ('file3', models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq')),
                ('file4', models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq')),
                ('test_file', models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq/test')),
                ('active', models.BooleanField(default=False)),
                ('vaqt_tugadi', models.BooleanField(default=False)),
                ('boshlanish_vaqti', models.DateField()),
                ('tugash_vaqti', models.DateField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
