# Generated by Django 5.1.6 on 2025-02-28 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topshiriq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='majburiytopshiriq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ozsohasidatopshiriq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ozxohishibilantopshiriq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qoshimchatopshiriq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='topshiriq_users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qoshimchatopshiriq',
            name='topshiriq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topshiriq.topshiriq'),
        ),
        migrations.AddField(
            model_name='ozsohasidatopshiriq',
            name='topshiriq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topshiriq.topshiriq'),
        ),
        migrations.AddField(
            model_name='majburiytopshiriq',
            name='topshiriq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topshiriq.topshiriq'),
        ),
    ]
