# Generated by Django 5.1.6 on 2025-04-09 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('matn', models.TextField(verbose_name='Savol matni')),
                ('variant_a', models.CharField(max_length=255)),
                ('variant_b', models.CharField(max_length=255)),
                ('variant_c', models.CharField(max_length=255)),
                ('variant_d', models.CharField(max_length=255)),
                ('togri_javob', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='To‘g‘ri javob')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='topshiriq',
            name='test_file',
        ),
        migrations.AddField(
            model_name='majburiytopshiriq',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='majburiytopshiriq',
            name='topshiriq',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='topshiriq.topshiriq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majburiytopshiriq',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ozsohasidatopshiriq',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozsohasidatopshiriq',
            name='topshiriq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topshiriq.topshiriq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ozsohasidatopshiriq',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ozxohishibilantopshiriq',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozxohishibilantopshiriq',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qoshimchatopshiriq',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qoshimchatopshiriq',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qoshimchatopshiriq',
            name='topshiriq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topshiriq.topshiriq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qoshimchatopshiriq',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='test_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='topshiriq_users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='majburiytopshiriq',
            name='tur',
            field=models.CharField(choices=[('ttjga_tashrif', 'ttjga_tashrif'), ('ijaraga_tashrif', 'ijaraga_tashrif'), ('tutorlik_soati', 'tutorlik_soati'), ('davra_suhbati', 'davra_suhbati'), ('tadbir', 'tadbir'), ('togarak', 'togarak'), ('ttjda_tadbir', 'ttjda_tadbir'), ('iqtidorli_talabam', 'iqtidorli_talabam'), ('oilaga_xat', 'oilaga_xat'), ('test', 'test')], max_length=30),
        ),
        migrations.AlterField(
            model_name='topshiriq',
            name='majburiy_topshiriq_turi',
            field=models.CharField(blank=True, choices=[('ttjga_tashrif', 'ttjga_tashrif'), ('ijaraga_tashrif', 'ijaraga_tashrif'), ('tutorlik_soati', 'tutorlik_soati'), ('davra_suhbati', 'davra_suhbati'), ('tadbir', 'tadbir'), ('togarak', 'togarak'), ('ttjda_tadbir', 'ttjda_tadbir'), ('iqtidorli_talabam', 'iqtidorli_talabam'), ('oilaga_xat', 'oilaga_xat'), ('test', 'test')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='TestJavob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('tanlangan_javob', models.CharField(max_length=1)),
                ('togri', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topshiriq.test')),
                ('topshiriq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='javoblar', to='topshiriq.topshiriq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestTopshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('boshlanish_vaqti', models.DateTimeField(blank=True)),
                ('tugash_vaqti', models.DateTimeField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topshiriq.test')),
                ('topshiriq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topshiriqlar', to='topshiriq.topshiriq')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
