# Generated by Django 5.1.6 on 2025-04-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0002_test_remove_topshiriq_test_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topshiriq',
            name='test_data',
        ),
    ]
