# Generated by Django 5.1.4 on 2025-02-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topshiriq',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq'),
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq'),
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq'),
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq'),
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='majburiytopshiriq',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='topshiriq/majburiy'),
        ),
        migrations.AlterField(
            model_name='majburiytopshiriq',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='topshiriq/majburiy'),
        ),
        migrations.AlterField(
            model_name='majburiytopshiriq',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='topshiriq/majburiy'),
        ),
        migrations.AlterField(
            model_name='majburiytopshiriq',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='topshiriq/majburiy'),
        ),
        migrations.AlterField(
            model_name='qoshimchatopshiriq',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha'),
        ),
        migrations.AlterField(
            model_name='qoshimchatopshiriq',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha'),
        ),
        migrations.AlterField(
            model_name='qoshimchatopshiriq',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha'),
        ),
        migrations.AlterField(
            model_name='qoshimchatopshiriq',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha'),
        ),
    ]
