# Generated by Django 5.1.6 on 2025-03-17 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0003_majburiytopshiriq_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talabalar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('fakultet', models.CharField(max_length=255)),
                ('yonalish', models.CharField(max_length=255)),
                ('kurs', models.CharField(max_length=255)),
                ('guruh', models.CharField(max_length=255)),
                ('familya', models.CharField(max_length=255)),
                ('ism', models.CharField(max_length=255)),
                ('jins', models.CharField(blank=True, choices=[('o`g`il', 'o`g`il'), ('qiz', 'qiz')], max_length=255)),
                ('tolov_status', models.CharField(max_length=255)),
                ('ijtimoiy_ximoya', models.CharField(blank=True, max_length=255)),
                ('ijtimoiy_daraja', models.CharField(blank=True, max_length=255)),
                ('iqdidorli_talaba', models.CharField(blank=True, max_length=255)),
                ('tyutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
