# Generated by Django 5.1.4 on 2025-02-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0004_alter_majburiytopshiriq_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majburiytopshiriq',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='qoshimchatopshiriq',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='topshiriq',
            options={'ordering': ['-created_at']},
        ),
    ]
