# Generated by Django 5.1.6 on 2025-04-09 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0004_testnatija'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testjavob',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testjavob',
            name='topshiriq',
        ),
        migrations.RemoveField(
            model_name='testjavob',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testtopshiriq',
            name='boshlanish_vaqti',
        ),
        migrations.RemoveField(
            model_name='testtopshiriq',
            name='tugash_vaqti',
        ),
        migrations.AddField(
            model_name='testjavob',
            name='test_topshiriq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='javoblar', to='topshiriq.testtopshiriq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testtopshiriq',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
