# Generated by Django 5.1.4 on 2025-02-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0005_alter_majburiytopshiriq_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majburiytopshiriq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='majburiytopshiriq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qoshimchatopshiriq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qoshimchatopshiriq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topshiriq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topshiriq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
