# Generated by Django 5.1.6 on 2025-03-20 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0006_remove_talabalar_fakultet_remove_talabalar_kurs_and_more'),
        ('users', '0004_fakultet_is_active_guruh_is_active_kurs_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='talabalar',
            name='nomer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='familya',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='guruh',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='talaba_guruh', to='users.guruh'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='ism',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='tyutor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Testlar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('savol', models.TextField()),
                ('a', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
                ('d', models.CharField(max_length=255)),
                ('togri', models.CharField(blank=True, max_length=255)),
                ('notogri', models.CharField(blank=True, max_length=255)),
                ('boshlanish', models.DateField()),
                ('tugash', models.DateField()),
                ('tyutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
