# Generated by Django 5.1.6 on 2025-03-22 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0007_talabalar_nomer_alter_talabalar_familya_and_more'),
        ('users', '0005_talaba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talabalar',
            name='guruh',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='talabalar1', to='users.guruh'),
        ),
    ]
