# Generated by Django 5.1.4 on 2025-02-03 05:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0007_topshiriq_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MajburiyTopshiriq',
            new_name='SuperAdminMajburiyTopshiriq',
        ),
        migrations.RenameModel(
            old_name='QoshimchaTopshiriq',
            new_name='SuperAdminQoshimchaTopshiriq',
        ),
        migrations.RenameModel(
            old_name='Topshiriq',
            new_name='SuperAdminTopshiriq',
        ),
    ]
