# Generated by Django 5.1.4 on 2025-02-03 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0008_rename_majburiytopshiriq_superadminmajburiytopshiriq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadminqoshimchatopshiriq',
            name='topshiriq',
        ),
        migrations.RemoveField(
            model_name='superadminqoshimchatopshiriq',
            name='user',
        ),
        migrations.RemoveField(
            model_name='superadmintopshiriq',
            name='users',
        ),
        migrations.CreateModel(
            name='Topshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topshiriq_turi', models.CharField(choices=[('majburiy', 'majburiy'), ('qoshimcha', 'qoshimcha')], max_length=30)),
                ('majburiy_topshiriq_turi', models.CharField(blank=True, choices=[('ttjga_tashrif', 'ttjga_tashrif'), ('ijaraga_tashrif', 'ijaraga_tashrif'), ('tutorlik_soati', 'tutorlik_soati'), ('davra_suhbati', 'davra_suhbati'), ('tadbir', 'tadbir'), ('ttjda_tadbir', 'ttjda_tadbir'), ('iqtidorli_talabam', 'iqtidorli_talabam'), ('oilaga_xat', 'oilaga_xat')], max_length=30, null=True)),
                ('topshiriq_soni', models.CharField(blank=True, max_length=2)),
                ('max_baxo', models.CharField(blank=True, max_length=3)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq')),
                ('file2', models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq')),
                ('file3', models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq')),
                ('file4', models.FileField(blank=True, null=True, upload_to='topshiriq/topshiriq')),
                ('active', models.BooleanField(default=True)),
                ('boshlanish_vaqti', models.DateField()),
                ('tugash_vaqti', models.DateField()),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topshiriq_users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QoshimchaTopshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baxo', models.CharField(blank=True, max_length=3)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file2', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file3', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file4', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topshiriq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topshiriq.topshiriq')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MajburiyTopshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tur', models.CharField(choices=[('ttjga_tashrif', 'ttjga_tashrif'), ('ijaraga_tashrif', 'ijaraga_tashrif'), ('tutorlik_soati', 'tutorlik_soati'), ('davra_suhbati', 'davra_suhbati'), ('tadbir', 'tadbir'), ('ttjda_tadbir', 'ttjda_tadbir'), ('iqtidorli_talabam', 'iqtidorli_talabam'), ('oilaga_xat', 'oilaga_xat')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('baxo', models.CharField(blank=True, max_length=3)),
                ('file1', models.FileField(blank=True, null=True, upload_to='topshiriq/majburiy')),
                ('file2', models.FileField(blank=True, null=True, upload_to='topshiriq/majburiy')),
                ('file3', models.FileField(blank=True, null=True, upload_to='topshiriq/majburiy')),
                ('file4', models.FileField(blank=True, null=True, upload_to='topshiriq/majburiy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topshiriq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topshiriq.topshiriq')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SuperAdminMajburiyTopshiriq',
        ),
        migrations.DeleteModel(
            name='SuperAdminQoshimchaTopshiriq',
        ),
        migrations.DeleteModel(
            name='SuperAdminTopshiriq',
        ),
    ]
