# Generated by Django 5.1.6 on 2025-03-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0008_alter_talabalar_guruh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talabalar',
        ),
    ]
