# Generated by Django 5.1.6 on 2025-04-04 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0009_delete_talabalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlar',
            name='topshiriq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topshiriq.topshiriq'),
            preserve_default=False,
        ),
    ]
