# Generated by Django 5.1.4 on 2025-02-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0009_remove_superadminqoshimchatopshiriq_topshiriq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majburiytopshiriq',
            name='baxo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qoshimchatopshiriq',
            name='baxo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topshiriq',
            name='max_baxo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topshiriq',
            name='topshiriq_soni',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='topshiriq',
            name='topshiriq_turi',
            field=models.CharField(choices=[('majburiy', 'majburiy'), ('qoshimcha', 'qoshimcha')], default='qoshimcha', max_length=30),
        ),
    ]
