# Generated by Django 5.1.6 on 2025-04-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0010_testlar_topshiriq'),
    ]

    operations = [
        migrations.AddField(
            model_name='qoshimchatopshiriq',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
