# Generated by Django 5.1.4 on 2025-02-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0010_alter_majburiytopshiriq_baxo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='majburiytopshiriq',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='majburiytopshiriq',
            name='baxolash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qoshimchatopshiriq',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qoshimchatopshiriq',
            name='baxolash',
            field=models.BooleanField(default=False),
        ),
    ]
