# Generated by Django 5.1.6 on 2025-04-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0011_qoshimchatopshiriq_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topshiriq',
            name='test_file',
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='test_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
