# Generated by Django 5.1.6 on 2025-04-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0012_remove_topshiriq_test_file_topshiriq_test_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlar',
            name='boshlanish',
        ),
        migrations.RemoveField(
            model_name='testlar',
            name='notogri',
        ),
        migrations.RemoveField(
            model_name='testlar',
            name='topshiriq',
        ),
        migrations.RemoveField(
            model_name='testlar',
            name='tugash',
        ),
        migrations.RemoveField(
            model_name='testlar',
            name='tyutor',
        ),
    ]
