# Generated by Django 5.1.4 on 2025-02-05 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0014_alter_topshiriq_admin_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OzSohasidaTopshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baxo', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file2', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file3', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file4', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('active', models.BooleanField(default=True)),
                ('baxolash', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OzXohishiBilanTopshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baxo', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file2', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file3', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('file4', models.FileField(blank=True, null=True, upload_to='topshiriq/qoshimcha')),
                ('active', models.BooleanField(default=True)),
                ('baxolash', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
