# Generated by Django 5.1.4 on 2025-02-05 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0016_topshiriq_test_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='topshiriq',
            name='topshiriq_turi',
            field=models.CharField(choices=[('majburiy', 'majburiy'), ('qoshimcha', 'qoshimcha'), ('test', 'test')], default='qoshimcha', max_length=30),
        ),
        migrations.CreateModel(
            name='TestTopshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baxo', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('baxolash', models.BooleanField(default=False)),
                ('topshiriq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topshiriq.topshiriq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
