# Generated by Django 5.1.6 on 2025-02-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0019_topshiriq_baxolandi_topshiriq_jarayonda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topshiriq',
            name='jarayonda',
        ),
    ]
