# Generated by Django 5.1.6 on 2025-02-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0020_remove_topshiriq_jarayonda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topshiriq',
            name='baxolandi',
        ),
    ]
