# Generated by Django 5.1.6 on 2025-02-15 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topshiriq', '0021_remove_topshiriq_baxolandi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majburiytopshiriq',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ozsohasidatopshiriq',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ozxohishibilantopshiriq',
            name='active',
        ),
        migrations.RemoveField(
            model_name='qoshimchatopshiriq',
            name='active',
        ),
        migrations.AddField(
            model_name='ozsohasidatopshiriq',
            name='topshiriq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topshiriq.topshiriq'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topshiriq',
            name='topshiriq_turi',
            field=models.CharField(choices=[('majburiy', 'majburiy'), ('qoshimcha', 'qoshimcha'), ('oz_sohasida', 'oz_sohasida')], default='qoshimcha', max_length=30),
        ),
    ]
